version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=supersecurepassword
    networks:
      - django_net

  web:
    build: .
    volumes:
      - static_volume_v2:/app/staticfiles
      - media_volume_v2:/app/mediafiles
    environment:
      - DEBUG=0
      - SECRET_KEY=ganti_dengan_key_produksi_anda
      - DATABASE_URL=postgres://djangouser:supersecurepassword@db:5432/djangodb
    depends_on:
      - db
    networks:
      - django_net

  nginx:
    image: nginx:alpine
    container_name: implementation_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume_v2:/app/staticfiles
      - media_volume_v2:/app/mediafiles
    depends_on:
      - web
    networks:
      - django_net
      - global_gateway_net

volumes:
  postgres_data:
  static_volume_v2:
  media_volume_v2:

networks:
  django_net:
    driver: bridge
  global_gateway_net:
    external: true