$file = "c:\Users\ASUS ROG\Project_anti_gravity\static\app.js"
$content = [System.IO.File]::ReadAllText($file)
$rn = "`r`n"

# ---- FIX 1: Pipeline Execution Status ----
$old1 = "        // 4. Pipeline Execution Status (Bar Chart)${rn}        createChart('pd-execution-chart', {${rn}            type: 'bar',${rn}            data: {${rn}                labels: ['User Data', 'Analytics', 'Reporting', 'Integration', 'Backup'],${rn}                datasets: [${rn}                    {${rn}                        label: 'Success',${rn}                        data: Array.from({length: 5}, () => Math.round(random(500, 1000))),${rn}                        backgroundColor: '#34d399',${rn}                        barThickness: 20${rn}                    },${rn}                    {${rn}                        label: 'Failed',${rn}                        data: Array.from({length: 5}, () => resolved ? 0 : Math.round(random(0, 50))),${rn}                        backgroundColor: '#f87171',${rn}                        barThickness: 20${rn}                    },${rn}                    {${rn}                        label: 'Pending',${rn}                        data: Array.from({length: 5}, () => Math.round(random(50, 200))),${rn}                        backgroundColor: '#fbbf24',${rn}                        barThickness: 20${rn}                    }${rn}                ]${rn}            },${rn}            options: {${rn}                responsive: true,${rn}                maintainAspectRatio: false,${rn}                plugins: { legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 8 } } },${rn}                scales: { y: { beginAtZero: true } }${rn}            }${rn}        });"

$new1 = "        // 4. Pipeline Execution Status (Bar Chart) - equal totals per category${rn}        const execTotal = 1000;${rn}        const execSuccess = [], execFailed = [], execPending = [];${rn}        for (let ei = 0; ei < 5; ei++) {${rn}            const failVal = resolved ? 0 : Math.round(random(10, 50));${rn}            const pendVal = Math.round(random(50, 150));${rn}            execSuccess.push(execTotal - failVal - pendVal);${rn}            execFailed.push(failVal);${rn}            execPending.push(pendVal);${rn}        }${rn}        createChart('pd-execution-chart', {${rn}            type: 'bar',${rn}            data: {${rn}                labels: ['User Data', 'Analytics', 'Reporting', 'Integration', 'Backup'],${rn}                datasets: [${rn}                    { label: 'Success', data: execSuccess, backgroundColor: '#34d399', barThickness: 20 },${rn}                    { label: 'Failed', data: execFailed, backgroundColor: '#f87171', barThickness: 20 },${rn}                    { label: 'Pending', data: execPending, backgroundColor: '#fbbf24', barThickness: 20 }${rn}                ]${rn}            },${rn}            options: {${rn}                responsive: true,${rn}                maintainAspectRatio: false,${rn}                plugins: { legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 8 } } },${rn}                scales: { x: { stacked: true }, y: { stacked: true, beginAtZero: true } }${rn}            }${rn}        });"

if ($content.Contains($old1)) {
    $content = $content.Replace($old1, $new1)
    Write-Host "FIX 1: Pipeline chart replaced OK"
} else {
    Write-Host "FIX 1: FAILED - target not matched"
}

# ---- FIX 2: Quality Dashboard Issues chart ----
$old2 = "    makeChart('dqa-issues-chart', {${rn}        type: 'bar',${rn}        data: {${rn}            labels: cats,${rn}            datasets: [${rn}                { label: 'Critical', data: catIssues.map(n => Math.max(0, Math.round(n * critFrac + seededRand(seed * 31, -0.5, 0.5)))), backgroundColor: '#f87171', barThickness: 14 },${rn}                { label: 'High',     data: catIssues.map(n => Math.round(n * 0.20 + seededRand(seed * 37, 0, 2))), backgroundColor: '#fbbf24', barThickness: 14 },${rn}                { label: 'Medium',   data: catIssues.map(n => Math.round(n * 0.35 + seededRand(seed * 41, 0, 3))), backgroundColor: '#60a5fa', barThickness: 14 },${rn}                { label: 'Low',      data: catIssues.map(n => Math.round(n * 0.40 + seededRand(seed * 43, 0, 2))), backgroundColor: '#34d399', barThickness: 14 }${rn}            ]${rn}        },${rn}        options: {${rn}            responsive: true, maintainAspectRatio: false,${rn}            plugins: { legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 8 } } },${rn}            scales: { y: { beginAtZero: true } }${rn}        }${rn}    });"

$new2 = "    // Equal totals per category${rn}    const issueFixedTotal = Math.max(issues, 10);${rn}    const issCritical = [], issHigh = [], issMedium = [], issLow = [];${rn}    cats.forEach((_, ci) => {${rn}        const crit = Math.max(0, Math.round(issueFixedTotal * critFrac + seededRand(seed * 31 + ci, -0.5, 0.5)));${rn}        const high = Math.round(issueFixedTotal * 0.20 + seededRand(seed * 37 + ci, 0, 2));${rn}        const med  = Math.round(issueFixedTotal * 0.35 + seededRand(seed * 41 + ci, 0, 2));${rn}        const low  = issueFixedTotal - crit - high - med;${rn}        issCritical.push(crit);${rn}        issHigh.push(high);${rn}        issMedium.push(Math.max(0, med));${rn}        issLow.push(Math.max(0, low));${rn}    });${rn}    makeChart('dqa-issues-chart', {${rn}        type: 'bar',${rn}        data: {${rn}            labels: cats,${rn}            datasets: [${rn}                { label: 'Critical', data: issCritical, backgroundColor: '#f87171', barThickness: 14 },${rn}                { label: 'High',     data: issHigh,     backgroundColor: '#fbbf24', barThickness: 14 },${rn}                { label: 'Medium',   data: issMedium,   backgroundColor: '#60a5fa', barThickness: 14 },${rn}                { label: 'Low',      data: issLow,      backgroundColor: '#34d399', barThickness: 14 }${rn}            ]${rn}        },${rn}        options: {${rn}            responsive: true, maintainAspectRatio: false,${rn}            plugins: { legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 8 } } },${rn}            scales: { x: { stacked: true }, y: { stacked: true, beginAtZero: true } }${rn}        }${rn}    });"

if ($content.Contains($old2)) {
    $content = $content.Replace($old2, $new2)
    Write-Host "FIX 2: Quality chart replaced OK"
} else {
    Write-Host "FIX 2: FAILED - target not matched"
}

[System.IO.File]::WriteAllText($file, $content)
Write-Host "File saved successfully."
