# Generated by Django 6.0.3 on 2026-05-29 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('activity', models.CharField(choices=[('todo', 'To Do'), ('in-progress', 'In Progress'), ('in-review', 'In Review'), ('done', 'Done')], default='todo', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completeness', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('validity', models.FloatField(default=0.0)),
                ('consistency', models.FloatField(default=0.0)),
                ('timeliness', models.FloatField(default=0.0)),
                ('latency', models.IntegerField(default=0)),
                ('throughput', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.dataset')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
