# Generated by Django 6.0.3 on 2026-05-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dataset_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltransaction',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='modeltransaction',
            name='input_features',
        ),
        migrations.RemoveField(
            model_name='modeltransaction',
            name='output_label',
        ),
        migrations.RemoveField(
            model_name='modeltransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='accuracy',
            field=models.CharField(default='0.0%', max_length=20),
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='input_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='model_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='output_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='source_type',
            field=models.CharField(choices=[('api', 'API'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='top_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='total_predictions',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='version',
            field=models.CharField(default='v1.0.0', max_length=50),
        ),
    ]
