# Generated by Django 6.0.3 on 2026-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_modeltransaction_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('issue_type', models.CharField(choices=[('quality', 'Low Quality Score'), ('pipeline', 'Pipeline Error'), ('missing_data', 'Missing / Incomplete Data'), ('schema_error', 'Schema Error'), ('drift', 'Data Drift Detected')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('quality_score', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
