# Generated by Django 6.0.3 on 2026-06-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dataset_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('category_color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
